# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 516d7322263884e070f2caece0e92793eb70f457cf8b18d2e438b3447f3ace1de27f5ba3bfc0d93871d7d09a6035f73a04df895f458829b92a37224355156d50

test:
  secret_key_base: 67ec720e87e07892542872aab22d455d8b7d75b7cd91d3eb4c55e78cac41431d0deec65e38f70bcff3430296f5879d9df4cbd58449da5630b9bd8dae0b07ea73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
